[pytest]
# Set the directory or file where tests are located (optional)
testpaths =
    tests

# Additional command-line options
addopts =
    --html=reports/test_report.html
    --self-contained-html
    --tb=short
    --strict-markers
    --ignore=report
    --ignore=reports
    --ignore=smoke_report
    --ignore=smoke_reports

# Register custom markers to avoid warnings
markers =
    dsm: mark tests related to the DeviceServiceMonitor
    smoke: mark tests as part of the smoke test suite
    regression: mark tests as part of the regression suite

# Logging (optional)
log_cli = true
log_cli_level = INFO
